# Generated by Django 4.2 on 2024-07-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_todos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todos',
            new_name='Todo',
        ),
    ]
