# Generated by Django 4.2 on 2024-07-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_user_id_todo_user_alter_todo_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
