# Generated by Django 4.2 on 2024-07-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_userdata_managers_remove_userdata_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='last_name',
        ),
    ]
