# Generated by Django 4.2 on 2024-07-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userdata_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
