# Generated by Django 4.2 on 2024-07-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_userdata_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
